# Generated by Django 4.2.3 on 2023-09-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pizzas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pizzas',
        ),
    ]
