# Generated by Django 4.2.3 on 2023-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('actual_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
